"""Application port for Inventory MCP persistence."""

from datetime import datetime
from typing import Protocol

from kindred_ai.domain.inventory import HouseholdItem, HouseholdPurchaseRequest, MedicationInventory, PurchaseRequest, Reminder


class InventoryRepository(Protocol):
    def get_inventory(self) -> list[MedicationInventory]: ...
    def get_item(self, medication_name: str) -> MedicationInventory | None: ...
    def add_purchase_request(self, *, request_id: str, medication_name: str, quantity: int, created_at: datetime) -> PurchaseRequest: ...
    def get_household_inventory(self) -> list[HouseholdItem]: ...
    def get_household_item(self, item_name: str) -> HouseholdItem | None: ...
    def add_household_purchase_request(self, *, request_id: str, item_name: str, quantity: int, created_at: datetime) -> HouseholdPurchaseRequest: ...
    def add_reminder(self, *, reminder_id: str, title: str, remind_at: datetime) -> Reminder: ...
